### ISSUE TITLE
How to run the application

### ISSUE THREAD

**Issue by wiz23424** [toothbrush/debounce-mac#11]
Hi, I know that this issue may seem quite dumb to most of you, but I'm struggling to understanding how exactly to run debounce on my mac. Can someone give me detailed instruction on how to do so?

**Comment by matthewcarbone** [comment]
@wiz23424 It's ok. We all struggled with this kinda thing at some point. You'll want to do the following:
1. Clone the repo.
2. Go into the repository in your Mac's terminal or your favorite command line program.
3. Build the executable (you'll likely just need to run `make` from within the directory).
4. Run the executable in a terminal (`./debounce`). That terminal will be hosting the process so you'll see a log of the output whenever keys bounce. You can also run it in the background via `./debounce &`, but I would recommend against that since you'll need to know the PID of the process to kill it later.

**Comment by wiz23424** [comment]
Thank you for the help! I bought a new keyboard and I don’t need debounce right now, but I’ll screenshot the instructions, just in case.
